services:
  - type: web
    name: wealthwise-backend
    env: docker
    dockerfilePath: wealthwise-backend/Dockerfile
    region: singapore
    plan: free
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: JWT_SECRET
        value: wealthwiseSecretKey
